### ISSUE TITLE
PA Review: User

### ISSUE THREAD

**Issue by xiaoyuny** [xiaoyuny/Airquq#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] When errors are displayed, the form adjusts properly (input boxes move up, sign in/sign up button moves down, and errors are displayed in between)
- [x] Smooth, bug free navigation
- [x] Login errors clears when switching from login form to sign up form (and vice-versa)
- [x] Going to a random route /#/oweiniouewbrviuwebv should redirect to either /, /login, or /signup
- [x] Errors should display for both /signup and/login.
- [x]  Errors should clear when moving between /signup and /login.
- [x]  Adequate and appropriate seeds

- [x]  Demo Login Works

**Comment by xnanodax** [comment]
Almost done!
- [x] Let's render the session errors red to make it more user friendly :)

**Comment by xnanodax** [comment]
When I click on sign up with empty fields, I receive a blank page and these errors:
![screen shot 2018-10-19 at 9 49 02 am](https://user-images.githubusercontent.com/20424731/47232338-444f6d80-d384-11e8-987b-76ab9c53346e.png)

**Comment by xiaoyuny** [comment]
Just found out it was because I accidentally deleted one of the photos I attach to new users when they sign up.. Fixed it!! Thank you so much!!
