### ISSUE TITLE
PA Review:Booking

### ISSUE THREAD

**Issue by xiaoyuny** [xiaoyuny/Airquq#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Booking form shows appropriate booking errors
- [x] Requires logged in before booking
- [x] After successful booking, redirects to trips index(booking history) page
- [x] Users can cancel booking in trips index page

**Comment by xnanodax** [comment]
- [ ] Watch out for this button :)
![screen shot 2018-10-17 at 9 45 22 am](https://user-images.githubusercontent.com/20424731/47103688-a7aa9580-d1f4-11e8-907f-6ab1e7090bb1.png)
- [ ] Let's get the index item closer to the airbnb's :)

airquq:
![screen shot 2018-10-17 at 10 09 45 am](https://user-images.githubusercontent.com/20424731/47103790-d6c10700-d1f4-11e8-8b76-a220c8350777.png)

airbnb: 
![screen shot 2018-10-17 at 10 09 35 am](https://user-images.githubusercontent.com/20424731/47103797-da548e00-d1f4-11e8-8d83-fee7e4dae1f5.png)

**Comment by xiaoyuny** [comment]
Oh I missed this comment.. I'll definitely find time to fix them later!
