### ISSUE TITLE
PA Review: Review

### ISSUE THREAD

**Issue by xiaoyuny** [xiaoyuny/Airquq#7]
- [x]  Backend: DB, model, controller, views
- [x]   Redux Loop: ajax, actions, reducer
- [x]   Presentational Components
- [x]   Styling
- [x]   Smooth, bug-free navigation
- [x]   Adequate and appropriate seeds
- [x]   Listing Index page, search result index page shows the total average rating in both numbers and stars
- [x]   Listing show page shows detailed average ratings

**Comment by xnanodax** [comment]
Let's fine tune the styling:

Watch out for the overlapping words w/ the stars:
![screen shot 2018-10-19 at 9 52 49 am](https://user-images.githubusercontent.com/20424731/47232647-17e82100-d385-11e8-846e-692ef5fb3bc2.png)


Airbnb:
![screen shot 2018-10-19 at 9 53 47 am](https://user-images.githubusercontent.com/20424731/47232626-09016e80-d385-11e8-8a49-bd54acb4317a.png)

Airquq:
![screen shot 2018-10-19 at 9 54 48 am](https://user-images.githubusercontent.com/20424731/47232631-0bfc5f00-d385-11e8-971d-190f30558ef2.png)
